version: "3"

services:
  # MySql主库
  mysqlmaster:
    hostname: mysqlmaster
    restart: always
    container_name: mysqlmaster
    image: sparklee/mysqlmaster:5.7
    build:
      context: ./mysql-master
      dockerfile: Dockerfile
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - kingshard
  # MySQL从库1
  mysqlslave1:
    hostname: mysqlslave1
    restart: always
    container_name: mysqlslave1
    image: sparklee/mysqlslave1:5.7
    build:
      context: ./mysql-slave-1
      dockerfile: Dockerfile
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - kingshard
  # MySQL从库2
  mysqlslave2:
    hostname: mysqlslave2
    restart: always
    container_name: mysqlslave2
    image: sparklee/mysqlslave2:5.7
    build:
      context: ./mysql-slave-2
      dockerfile: Dockerfile
    ports:
      - "33062:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - kingshard
  # MySql主库2
  mysqlmaster2:
    hostname: mysqlmaster2
    restart: always
    container_name: mysqlmaster2
    image: sparklee/mysqlmaster2:5.7
    build:
      context: ./mysql-master-2
      dockerfile: Dockerfile
    ports:
      - "33070:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - kingshard
networks:
  kingshard:
